INSERT INTO Funcionario VALUES(7,'Beto Fabri','beto.fabri@omelete.com','vp_socio',1,1);
INSERT INTO Funcionario VALUES(8,'Camila Ramos','camila.ramos@omelete.com','diretoria',1,0);
INSERT INTO Funcionario VALUES(9,'Diego Lima','diego.lima@omelete.com','geral',0,0);
INSERT INTO Convidado VALUES(19,'Ana Beltrão','ana.beltrao@warnerbros.com',NULL,'Warner Bros.',NULL,NULL,NULL,0,0);
INSERT INTO Convidado VALUES(20,'Henrique Sato',NULL,'+5511955554444',NULL,NULL,NULL,NULL,0,0);
INSERT INTO Convidado VALUES(21,'Bruno Okamoto','bruno.okamoto@netflix.com',NULL,'Netflix','Diretor de Conteúdo','1988-03-14T00:00:00.000+00:00','2026-06-08T19:19:02.105+00:00',0,0);
INSERT INTO Convidado VALUES(22,'Carla Mendes','carla.mendes@globo.com',NULL,'Globo',NULL,NULL,NULL,0,0);
INSERT INTO Convidado VALUES(23,'Davi Fontes',NULL,'+5511987654321',NULL,NULL,NULL,NULL,0,0);
INSERT INTO Convidado VALUES(24,'Elisa Prado','elisa.prado@paramount.com',NULL,'Paramount','Head de Distribuição','1985-11-02T00:00:00.000+00:00','2026-06-05T19:19:02.111+00:00',0,1);
INSERT INTO Convidado VALUES(25,'Fábio Quintela','fabio.q@ubisoft.com',NULL,'Ubisoft','Brand Manager','1990-07-21T00:00:00.000+00:00','2026-06-01T19:19:02.115+00:00',0,1);
INSERT INTO Convidado VALUES(26,'Luís Hernandez','luis.hernandez@hbo.com',NULL,'HBO','VP de Programação','1979-05-30T00:00:00.000+00:00','2026-06-09T19:19:02.117+00:00',0,0);
INSERT INTO Convidado VALUES(27,'Gabi Torres',NULL,'+5511912345678',NULL,NULL,'1995-09-12T00:00:00.000+00:00','2026-06-10T19:19:02.121+00:00',0,0);
INSERT INTO Convite VALUES(21,7,19,'email','pendente','2026-06-17T19:19:02.085+00:00',1,'2026-06-10T19:19:02.086+00:00','tok-ana');
INSERT INTO Convite VALUES(22,9,20,'whatsapp','pendente','2026-06-16T19:19:02.103+00:00',0,'2026-06-09T19:19:02.103+00:00','tok-henrique');
INSERT INTO Convite VALUES(23,8,21,'email,whatsapp','cadastrado','2026-06-14T19:19:02.106+00:00',0,'2026-06-07T19:19:02.106+00:00','tok-bruno');
INSERT INTO Convite VALUES(24,8,22,'email','expirado','2026-06-09T19:19:02.109+00:00',0,'2026-06-02T19:19:02.109+00:00','tok-carla');
INSERT INTO Convite VALUES(25,9,23,'whatsapp','cancelado','2026-06-13T19:19:02.110+00:00',0,'2026-06-06T19:19:02.110+00:00','tok-davi');
INSERT INTO Convite VALUES(26,7,24,'email','cadastrado','2026-06-12T19:19:02.112+00:00',1,'2026-06-05T19:19:02.112+00:00','tok-elisa');
INSERT INTO Convite VALUES(27,8,25,'email','cadastrado','2026-06-08T19:19:02.115+00:00',0,'2026-06-01T19:19:02.115+00:00','tok-fabio');
INSERT INTO Convite VALUES(28,7,26,'email','cadastrado','2026-06-15T19:19:02.117+00:00',0,'2026-06-08T19:19:02.117+00:00','tok-luis-beto');
INSERT INTO Convite VALUES(29,8,26,'email','cadastrado','2026-06-15T19:19:02.120+00:00',1,'2026-06-09T19:19:02.120+00:00','tok-luis-camila');
INSERT INTO Convite VALUES(30,9,27,'whatsapp','cadastrado','2026-06-16T19:19:02.122+00:00',0,'2026-06-09T19:19:02.122+00:00','tok-gabi');
INSERT INTO ConviteParcela VALUES(21,21,'corporativo','todos_os_dias',2,1);
INSERT INTO ConviteParcela VALUES(22,22,'pessoal','domingo',1,0);
INSERT INTO ConviteParcela VALUES(23,23,'corporativo','sabado',2,0);
INSERT INTO ConviteParcela VALUES(24,24,'corporativo','domingo',1,0);
INSERT INTO ConviteParcela VALUES(25,25,'pessoal','sexta',1,0);
INSERT INTO ConviteParcela VALUES(26,26,'corporativo','quinta',1,1);
INSERT INTO ConviteParcela VALUES(27,27,'corporativo','todos_os_dias',1,0);
INSERT INTO ConviteParcela VALUES(28,28,'pessoal','sabado',2,0);
INSERT INTO ConviteParcela VALUES(29,29,'corporativo','sexta',1,0);
INSERT INTO ConviteParcela VALUES(30,30,'pessoal','domingo',1,0);
INSERT INTO Codigo VALUES(255,'OMLT-BF-SPO1','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(256,'OMLT-BF-SPO2','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(257,'OMLT-BF-SPO3','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(258,'OMLT-BF-SPO4','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(259,'OMLT-BF-SPO5','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(260,'OMLT-BF-SPO6','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(261,'OMLT-BF-SPO7','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(262,'OMLT-BF-SPO8','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(263,'OMLT-BF-SPO9','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(264,'OMLT-BF-SPO10','spoiler_night','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(265,'OMLT-BF-QUI1','quinta','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(266,'OMLT-BF-QUI2','quinta','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(267,'OMLT-BF-QUI3','quinta','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(268,'OMLT-BF-QUI4','quinta','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(269,'OMLT-BF-SEX1','sexta','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(270,'OMLT-BF-SEX2','sexta','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(271,'OMLT-BF-SEX3','sexta','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(272,'OMLT-BF-SEX4','sexta','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(273,'OMLT-BF-SAB1','sabado','pessoal',7,'entregue',28,NULL,NULL);
INSERT INTO Codigo VALUES(274,'OMLT-BF-SAB2','sabado','pessoal',7,'entregue',28,NULL,NULL);
INSERT INTO Codigo VALUES(275,'OMLT-BF-SAB3','sabado','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(276,'OMLT-BF-SAB4','sabado','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(277,'OMLT-BF-DOM1','domingo','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(278,'OMLT-BF-DOM2','domingo','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(279,'OMLT-BF-DOM3','domingo','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(280,'OMLT-BF-DOM4','domingo','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(281,'OMLT-BF-TOD1','todos_os_dias','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(282,'OMLT-BF-TOD2','todos_os_dias','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(283,'OMLT-BF-TOD3','todos_os_dias','pessoal',7,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(284,'OMLT-CR-SPO1','spoiler_night','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(285,'OMLT-CR-SPO2','spoiler_night','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(286,'OMLT-CR-SPO3','spoiler_night','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(287,'OMLT-CR-SPO4','spoiler_night','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(288,'OMLT-CR-QUI1','quinta','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(289,'OMLT-CR-QUI2','quinta','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(290,'OMLT-CR-SEX1','sexta','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(291,'OMLT-CR-SEX2','sexta','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(292,'OMLT-CR-SEX3','sexta','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(293,'OMLT-CR-SAB1','sabado','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(294,'OMLT-CR-SAB2','sabado','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(295,'OMLT-CR-SAB3','sabado','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(296,'OMLT-CR-DOM1','domingo','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(297,'OMLT-CR-DOM2','domingo','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(298,'OMLT-CR-DOM3','domingo','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(299,'OMLT-CR-TOD1','todos_os_dias','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(300,'OMLT-CR-TOD2','todos_os_dias','pessoal',8,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(301,'OMLT-DL-SPO1','spoiler_night','pessoal',9,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(302,'OMLT-DL-SPO2','spoiler_night','pessoal',9,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(303,'OMLT-DL-SEX1','sexta','pessoal',9,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(304,'OMLT-DL-SEX2','sexta','pessoal',9,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(305,'OMLT-DL-SAB1','sabado','pessoal',9,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(306,'OMLT-DL-SAB2','sabado','pessoal',9,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(307,'OMLT-DL-DOM1','domingo','pessoal',9,'reservado',22,NULL,NULL);
INSERT INTO Codigo VALUES(308,'OMLT-DL-DOM2','domingo','pessoal',9,'entregue',30,NULL,NULL);
INSERT INTO Codigo VALUES(309,'OMLT-DL-TOD1','todos_os_dias','pessoal',9,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(310,'CCXP-CORP-SPO001','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(311,'CCXP-CORP-SPO002','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(312,'CCXP-CORP-SPO003','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(313,'CCXP-CORP-SPO004','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(314,'CCXP-CORP-SPO005','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(315,'CCXP-CORP-SPO006','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(316,'CCXP-CORP-SPO007','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(317,'CCXP-CORP-SPO008','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(318,'CCXP-CORP-SPO009','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(319,'CCXP-CORP-SPO010','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(320,'CCXP-CORP-SPO011','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(321,'CCXP-CORP-SPO012','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(322,'CCXP-CORP-QUI001','quinta','corporativo',NULL,'entregue',26,NULL,NULL);
INSERT INTO Codigo VALUES(323,'CCXP-CORP-QUI002','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(324,'CCXP-CORP-QUI003','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(325,'CCXP-CORP-QUI004','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(326,'CCXP-CORP-QUI005','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(327,'CCXP-CORP-QUI006','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(328,'CCXP-CORP-QUI007','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(329,'CCXP-CORP-QUI008','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(330,'CCXP-CORP-QUI009','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(331,'CCXP-CORP-QUI010','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(332,'CCXP-CORP-QUI011','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(333,'CCXP-CORP-QUI012','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(334,'CCXP-CORP-SEX001','sexta','corporativo',NULL,'entregue',29,NULL,NULL);
INSERT INTO Codigo VALUES(335,'CCXP-CORP-SEX002','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(336,'CCXP-CORP-SEX003','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(337,'CCXP-CORP-SEX004','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(338,'CCXP-CORP-SEX005','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(339,'CCXP-CORP-SEX006','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(340,'CCXP-CORP-SEX007','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(341,'CCXP-CORP-SEX008','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(342,'CCXP-CORP-SEX009','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(343,'CCXP-CORP-SEX010','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(344,'CCXP-CORP-SEX011','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(345,'CCXP-CORP-SEX012','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(346,'CCXP-CORP-SAB001','sabado','corporativo',NULL,'entregue',23,NULL,NULL);
INSERT INTO Codigo VALUES(347,'CCXP-CORP-SAB002','sabado','corporativo',NULL,'entregue',23,NULL,NULL);
INSERT INTO Codigo VALUES(348,'CCXP-CORP-SAB003','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(349,'CCXP-CORP-SAB004','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(350,'CCXP-CORP-SAB005','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(351,'CCXP-CORP-SAB006','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(352,'CCXP-CORP-SAB007','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(353,'CCXP-CORP-SAB008','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(354,'CCXP-CORP-SAB009','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(355,'CCXP-CORP-SAB010','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(356,'CCXP-CORP-SAB011','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(357,'CCXP-CORP-SAB012','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(358,'CCXP-CORP-DOM001','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(359,'CCXP-CORP-DOM002','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(360,'CCXP-CORP-DOM003','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(361,'CCXP-CORP-DOM004','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(362,'CCXP-CORP-DOM005','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(363,'CCXP-CORP-DOM006','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(364,'CCXP-CORP-DOM007','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(365,'CCXP-CORP-DOM008','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(366,'CCXP-CORP-DOM009','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(367,'CCXP-CORP-DOM010','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(368,'CCXP-CORP-DOM011','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(369,'CCXP-CORP-DOM012','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(370,'CCXP-CORP-TOD001','todos_os_dias','corporativo',NULL,'reservado',21,NULL,NULL);
INSERT INTO Codigo VALUES(371,'CCXP-CORP-TOD002','todos_os_dias','corporativo',NULL,'reservado',21,NULL,NULL);
INSERT INTO Codigo VALUES(372,'CCXP-CORP-TOD003','todos_os_dias','corporativo',NULL,'resgatado',27,'2026-06-09T19:19:02.116+00:00',NULL);
INSERT INTO Codigo VALUES(373,'CCXP-CORP-TOD004','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(374,'CCXP-CORP-TOD005','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(375,'CCXP-CORP-TOD006','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(376,'CCXP-CORP-TOD007','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(377,'CCXP-CORP-TOD008','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(378,'CCXP-CORP-TOD009','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(379,'CCXP-CORP-TOD010','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(380,'CCXP-CORP-TOD011','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(381,'CCXP-CORP-TOD012','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO ComunicacaoLog VALUES(17,19,'transacional','convite','email','enviado','2026-06-10T19:19:02.125+00:00');
INSERT INTO ComunicacaoLog VALUES(18,21,'transacional','convite','email','enviado','2026-06-07T19:19:02.126+00:00');
INSERT INTO ComunicacaoLog VALUES(19,21,'transacional','instrucao_resgate','email','enviado','2026-06-08T19:19:02.126+00:00');
INSERT INTO ComunicacaoLog VALUES(20,22,'transacional','convite','email','enviado','2026-06-02T19:19:02.127+00:00');
INSERT INTO ComunicacaoLog VALUES(21,22,'transacional','lembrete_cadastro','email','enviado','2026-06-05T19:19:02.127+00:00');
INSERT INTO ComunicacaoLog VALUES(22,22,'transacional','aviso_expiracao','email','enviado','2026-06-08T19:19:02.127+00:00');
INSERT INTO ComunicacaoLog VALUES(23,24,'regua','d-7_falta_uma_semana','email','enviado','2026-06-10T19:19:02.128+00:00');
INSERT INTO ComunicacaoLog VALUES(24,26,'transacional','convite','email','enviado','2026-06-08T19:19:02.128+00:00');
INSERT INTO ReguaPasso VALUES(1,'transacional',1,'Convite','imediato',NULL,'email,whatsapp',NULL,'Você foi convidado pra CCXP26','Olá, {{nome}}! {{host}} convidou você pra CCXP26 (03 a 06/dez, São Paulo Expo) com {{qtd}} ingresso(s): {{tipos}}. Complete seu cadastro pra receber os códigos: {{link}}',1);
INSERT INTO ReguaPasso VALUES(2,'transacional',2,'Lembrete de cadastro','D+3',NULL,'email,whatsapp','pular_se_cadastrado','Seus ingressos da CCXP26 esperam por você','{{nome}}, seus {{qtd}} ingresso(s) seguem reservados, mas o cadastro ainda não foi concluído. Leva 1 minuto: {{link}}',1);
INSERT INTO ReguaPasso VALUES(3,'transacional',3,'Aviso de expiração','D+6',NULL,'email,whatsapp','pular_se_cadastrado','Último dia: seu convite expira amanhã','{{nome}}, seu convite pra CCXP26 expira amanhã e os ingressos voltam ao pool. Garanta os seus: {{link}}',1);
INSERT INTO ReguaPasso VALUES(4,'transacional',4,'Instrução de resgate','após cadastro',NULL,'email',NULL,'Como resgatar seus ingressos na Mundo Ticket','{{nome}}, seus códigos estão na sua carteira. Resgate na Mundo Ticket com o passo a passo: {{link}}. Qualquer dúvida, fale com {{host}}.',1);
INSERT INTO ReguaPasso VALUES(5,'regua',1,'Falta uma semana','D-7','2026-11-26','email',NULL,'Falta uma semana pra CCXP26','{{nome}}, em 7 dias a CCXP26 abre os portões no São Paulo Expo. Como chegar, por onde entrar e o que levar: tudo neste guia. Seus ingressos: {{tipos}}.',1);
INSERT INTO ReguaPasso VALUES(6,'regua',2,'Lembrete de resgate','D-3','2026-11-30','email,whatsapp','pular_se_resgatado','Já resgatou seus ingressos?','{{nome}}, faltam 3 dias e seus códigos ainda não foram resgatados na Mundo Ticket. Resolve agora em 2 minutos: {{link}}. Mapa do evento em anexo.',1);
INSERT INTO ReguaPasso VALUES(7,'regua',3,'Véspera: agenda do dia','D-1','2026-12-02','email',NULL,'Amanhã tem CCXP26: sua agenda','{{nome}}, amanhã começa! Agenda do dia, dicas práticas e o lounge VIP Omelete te esperando. Credenciamento VIP abre 1h antes dos portões.',1);
INSERT INTO ReguaPasso VALUES(8,'regua',4,'É hoje','Dia 1','2026-12-03','whatsapp',NULL,'É hoje! CCXP26 abre às 12h','{{nome}}, chegou o dia. Destaques de hoje no Palco Thunder, entrada VIP pela entrada Sul. Bom evento!',1);
INSERT INTO ReguaPasso VALUES(9,'transacional',1,'Convite','imediato',NULL,'email,whatsapp',NULL,'Você foi convidado pra CCXP26','Olá, {{nome}}! {{host}} convidou você pra CCXP26 (03 a 06/dez, São Paulo Expo) com {{qtd}} ingresso(s): {{tipos}}. Complete seu cadastro pra receber os códigos: {{link}}',1);
INSERT INTO ReguaPasso VALUES(10,'transacional',2,'Lembrete de cadastro','D+3',NULL,'email,whatsapp','pular_se_cadastrado','Seus ingressos da CCXP26 esperam por você','{{nome}}, seus {{qtd}} ingresso(s) seguem reservados, mas o cadastro ainda não foi concluído. Leva 1 minuto: {{link}}',1);
INSERT INTO ReguaPasso VALUES(11,'transacional',3,'Aviso de expiração','D+6',NULL,'email,whatsapp','pular_se_cadastrado','Último dia: seu convite expira amanhã','{{nome}}, seu convite pra CCXP26 expira amanhã e os ingressos voltam ao pool. Garanta os seus: {{link}}',1);
INSERT INTO ReguaPasso VALUES(12,'transacional',4,'Instrução de resgate','após cadastro',NULL,'email',NULL,'Como resgatar seus ingressos na Mundo Ticket','{{nome}}, seus códigos estão na sua carteira. Resgate na Mundo Ticket com o passo a passo: {{link}}. Qualquer dúvida, fale com {{host}}.',1);
INSERT INTO ReguaPasso VALUES(13,'regua',1,'Falta uma semana','D-7','2026-11-26','email',NULL,'Falta uma semana pra CCXP26','{{nome}}, em 7 dias a CCXP26 abre os portões no São Paulo Expo. Como chegar, por onde entrar e o que levar: tudo neste guia. Seus ingressos: {{tipos}}.',1);
INSERT INTO ReguaPasso VALUES(14,'regua',2,'Lembrete de resgate','D-3','2026-11-30','email,whatsapp','pular_se_resgatado','Já resgatou seus ingressos?','{{nome}}, faltam 3 dias e seus códigos ainda não foram resgatados na Mundo Ticket. Resolve agora em 2 minutos: {{link}}. Mapa do evento em anexo.',1);
INSERT INTO ReguaPasso VALUES(15,'regua',3,'Véspera: agenda do dia','D-1','2026-12-02','email',NULL,'Amanhã tem CCXP26: sua agenda','{{nome}}, amanhã começa! Agenda do dia, dicas práticas e o lounge VIP Omelete te esperando. Credenciamento VIP abre 1h antes dos portões.',1);
INSERT INTO ReguaPasso VALUES(16,'regua',4,'É hoje','Dia 1','2026-12-03','whatsapp',NULL,'É hoje! CCXP26 abre às 12h','{{nome}}, chegou o dia. Destaques de hoje no Palco Thunder, entrada VIP pela entrada Sul. Bom evento!',1);
INSERT INTO ReguaPasso VALUES(17,'pos_evento',1,'Agradecimento + fotos','D+1','2026-12-07','email',NULL,'Obrigado por viver a CCXP26 com a gente','{{nome}}, foi incrível ter você na CCXP26. As fotos do lounge VIP Omelete já estão disponíveis na sua conta: {{link}}',1);
INSERT INTO ReguaPasso VALUES(18,'pos_evento',2,'Pesquisa de satisfação','D+3','2026-12-09','email',NULL,'2 minutos: como foi sua CCXP26?','{{nome}}, sua opinião define a próxima edição. Responda a pesquisa rápida (NPS + 3 perguntas): {{link}}',1);
INSERT INTO ReguaPasso VALUES(19,'pos_evento',3,'Números + after movie','D+7','2026-12-13','email',NULL,'CCXP26 em números (e o after movie)','{{nome}}, a CCXP26 em números: público, palcos e os melhores momentos no after movie. Assista e compartilhe: {{link}}',1);
INSERT INTO AgendaItem VALUES(9,'2026-12-03','11:00','Abertura dos portões','Credenciamento VIP na entrada Sul do São Paulo Expo.');
INSERT INTO AgendaItem VALUES(10,'2026-12-03','14:00','Painel de abertura · Palco Thunder','Apresentação oficial da CCXP26.');
INSERT INTO AgendaItem VALUES(11,'2026-12-05','16:00','Painel principal · Palco Thunder','Convidado internacional surpresa.');
INSERT INTO AgendaItem VALUES(12,'2026-12-06','18:00','Encerramento','Último dia: recap e agradecimentos.');
INSERT INTO DominioBloqueado VALUES(27,'gmail.com');
INSERT INTO DominioBloqueado VALUES(28,'hotmail.com');
INSERT INTO DominioBloqueado VALUES(29,'outlook.com');
INSERT INTO DominioBloqueado VALUES(30,'yahoo.com');
INSERT INTO DominioBloqueado VALUES(31,'icloud.com');
INSERT INTO DominioBloqueado VALUES(32,'live.com');
INSERT INTO DominioBloqueado VALUES(33,'msn.com');
INSERT INTO DominioBloqueado VALUES(34,'aol.com');
INSERT INTO DominioBloqueado VALUES(35,'proton.me');
INSERT INTO DominioBloqueado VALUES(36,'protonmail.com');
INSERT INTO DominioBloqueado VALUES(37,'gmx.com');
INSERT INTO DominioBloqueado VALUES(38,'mail.com');
INSERT INTO DominioBloqueado VALUES(39,'yandex.com');
INSERT INTO AuditLog VALUES(9,7,'import_planilha_mestre','planilha','55 códigos pessoais importados (Modo A)','2026-05-30T19:19:02.137+00:00');
INSERT INTO AuditLog VALUES(10,7,'import_lote_corporativo','planilha','72 códigos corporativos importados','2026-05-30T19:19:02.137+00:00');
INSERT INTO AuditLog VALUES(11,9,'cancelar_convite','convite:Davi Fontes','1 código devolvido ao pool pessoal','2026-06-07T19:19:02.137+00:00');
INSERT INTO AuditLog VALUES(12,7,'editar_flag_vip','convidado:Elisa Prado','vip_omelete: false → true','2026-06-06T19:19:02.137+00:00');
INSERT INTO Config VALUES('expiracao_dias','7');
INSERT INTO Config VALUES('evento_inicio','2026-12-03');
INSERT INTO Config VALUES('evento_fim','2026-12-06');
INSERT INTO Config VALUES('evento_local','São Paulo Expo');
INSERT INTO Config VALUES('link_mundo_ticket','https://mundoticket.com.br/ccxp26/resgate');
