INSERT INTO Funcionario VALUES(10,'Beto Fabri','beto.fabri@omelete.com','vp_socio',1,1);
INSERT INTO Funcionario VALUES(11,'Camila Ramos','camila.ramos@omelete.com','diretoria',1,0);
INSERT INTO Funcionario VALUES(12,'Diego Lima','diego.lima@omelete.com','geral',0,0);
INSERT INTO Convidado VALUES(28,'Ana Beltrão','ana.beltrao@warnerbros.com',NULL,'Warner Bros.',NULL,NULL,NULL,0,0);
INSERT INTO Convidado VALUES(29,'Henrique Sato',NULL,'+5511955554444',NULL,NULL,NULL,NULL,0,0);
INSERT INTO Convidado VALUES(30,'Bruno Okamoto','bruno.okamoto@netflix.com',NULL,'Netflix','Diretor de Conteúdo','1988-03-14T00:00:00.000+00:00','2026-06-08T21:59:01.614+00:00',0,0);
INSERT INTO Convidado VALUES(31,'Carla Mendes','carla.mendes@globo.com',NULL,'Globo',NULL,NULL,NULL,0,0);
INSERT INTO Convidado VALUES(32,'Davi Fontes',NULL,'+5511987654321',NULL,NULL,NULL,NULL,0,0);
INSERT INTO Convidado VALUES(33,'Elisa Prado','elisa.prado@paramount.com',NULL,'Paramount','Head de Distribuição','1985-11-02T00:00:00.000+00:00','2026-06-05T21:59:01.620+00:00',0,1);
INSERT INTO Convidado VALUES(34,'Fábio Quintela','fabio.q@ubisoft.com',NULL,'Ubisoft','Brand Manager','1990-07-21T00:00:00.000+00:00','2026-06-01T21:59:01.623+00:00',0,1);
INSERT INTO Convidado VALUES(35,'Luís Hernandez','luis.hernandez@hbo.com',NULL,'HBO','VP de Programação','1979-05-30T00:00:00.000+00:00','2026-06-09T21:59:01.626+00:00',0,0);
INSERT INTO Convidado VALUES(36,'Gabi Torres',NULL,'+5511912345678',NULL,NULL,'1995-09-12T00:00:00.000+00:00','2026-06-10T21:59:01.629+00:00',0,0);
INSERT INTO Convite VALUES(31,10,28,'email','pendente','2026-06-17T21:59:01.596+00:00',1,'2026-06-10T21:59:01.596+00:00','tok-ana');
INSERT INTO Convite VALUES(32,12,29,'whatsapp','pendente','2026-06-16T21:59:01.613+00:00',0,'2026-06-09T21:59:01.613+00:00','tok-henrique');
INSERT INTO Convite VALUES(33,11,30,'email,whatsapp','cadastrado','2026-06-14T21:59:01.615+00:00',0,'2026-06-07T21:59:01.615+00:00','tok-bruno');
INSERT INTO Convite VALUES(34,11,31,'email','expirado','2026-06-09T21:59:01.618+00:00',0,'2026-06-02T21:59:01.618+00:00','tok-carla');
INSERT INTO Convite VALUES(35,12,32,'whatsapp','cancelado','2026-06-13T21:59:01.620+00:00',0,'2026-06-06T21:59:01.620+00:00','tok-davi');
INSERT INTO Convite VALUES(36,10,33,'email','cadastrado','2026-06-12T21:59:01.621+00:00',1,'2026-06-05T21:59:01.621+00:00','tok-elisa');
INSERT INTO Convite VALUES(37,11,34,'email','cadastrado','2026-06-08T21:59:01.624+00:00',0,'2026-06-01T21:59:01.624+00:00','tok-fabio');
INSERT INTO Convite VALUES(38,10,35,'email','cadastrado','2026-06-15T21:59:01.626+00:00',0,'2026-06-08T21:59:01.626+00:00','tok-luis-beto');
INSERT INTO Convite VALUES(39,11,35,'email','cadastrado','2026-06-15T21:59:01.628+00:00',1,'2026-06-09T21:59:01.628+00:00','tok-luis-camila');
INSERT INTO Convite VALUES(40,12,36,'whatsapp','cadastrado','2026-06-16T21:59:01.630+00:00',0,'2026-06-09T21:59:01.630+00:00','tok-gabi');
INSERT INTO ConviteParcela VALUES(31,31,'corporativo','todos_os_dias',2,1);
INSERT INTO ConviteParcela VALUES(32,32,'pessoal','domingo',1,0);
INSERT INTO ConviteParcela VALUES(33,33,'corporativo','sabado',2,0);
INSERT INTO ConviteParcela VALUES(34,34,'corporativo','domingo',1,0);
INSERT INTO ConviteParcela VALUES(35,35,'pessoal','sexta',1,0);
INSERT INTO ConviteParcela VALUES(36,36,'corporativo','quinta',1,1);
INSERT INTO ConviteParcela VALUES(37,37,'corporativo','todos_os_dias',1,0);
INSERT INTO ConviteParcela VALUES(38,38,'pessoal','sabado',2,0);
INSERT INTO ConviteParcela VALUES(39,39,'corporativo','sexta',1,0);
INSERT INTO ConviteParcela VALUES(40,40,'pessoal','domingo',1,0);
INSERT INTO Codigo VALUES(382,'OMLT-BF-SAB1','sabado','pessoal',10,'entregue',38,NULL,NULL);
INSERT INTO Codigo VALUES(383,'OMLT-BF-SAB2','sabado','pessoal',10,'entregue',38,NULL,NULL);
INSERT INTO Codigo VALUES(384,'OMLT-CR-SPO1','spoiler_night','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(385,'OMLT-CR-SPO2','spoiler_night','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(386,'OMLT-CR-SPO3','spoiler_night','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(387,'OMLT-CR-SPO4','spoiler_night','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(388,'OMLT-CR-QUI1','quinta','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(389,'OMLT-CR-QUI2','quinta','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(390,'OMLT-CR-SEX1','sexta','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(391,'OMLT-CR-SEX2','sexta','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(392,'OMLT-CR-SEX3','sexta','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(393,'OMLT-CR-SAB1','sabado','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(394,'OMLT-CR-SAB2','sabado','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(395,'OMLT-CR-SAB3','sabado','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(396,'OMLT-CR-DOM1','domingo','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(397,'OMLT-CR-DOM2','domingo','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(398,'OMLT-CR-DOM3','domingo','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(399,'OMLT-CR-TOD1','todos_os_dias','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(400,'OMLT-CR-TOD2','todos_os_dias','pessoal',11,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(401,'OMLT-DL-SPO1','spoiler_night','pessoal',12,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(402,'OMLT-DL-SPO2','spoiler_night','pessoal',12,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(403,'OMLT-DL-SEX1','sexta','pessoal',12,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(404,'OMLT-DL-SEX2','sexta','pessoal',12,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(405,'OMLT-DL-SAB1','sabado','pessoal',12,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(406,'OMLT-DL-SAB2','sabado','pessoal',12,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(407,'OMLT-DL-DOM1','domingo','pessoal',12,'reservado',32,NULL,NULL);
INSERT INTO Codigo VALUES(408,'OMLT-DL-DOM2','domingo','pessoal',12,'entregue',40,NULL,NULL);
INSERT INTO Codigo VALUES(409,'OMLT-DL-TOD1','todos_os_dias','pessoal',12,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(410,'CCXP-CORP-SPO001','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(411,'CCXP-CORP-SPO002','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(412,'CCXP-CORP-SPO003','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(413,'CCXP-CORP-SPO004','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(414,'CCXP-CORP-SPO005','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(415,'CCXP-CORP-SPO006','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(416,'CCXP-CORP-SPO007','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(417,'CCXP-CORP-SPO008','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(418,'CCXP-CORP-SPO009','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(419,'CCXP-CORP-SPO010','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(420,'CCXP-CORP-SPO011','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(421,'CCXP-CORP-SPO012','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(422,'CCXP-CORP-QUI001','quinta','corporativo',NULL,'entregue',36,NULL,NULL);
INSERT INTO Codigo VALUES(423,'CCXP-CORP-QUI002','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(424,'CCXP-CORP-QUI003','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(425,'CCXP-CORP-QUI004','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(426,'CCXP-CORP-QUI005','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(427,'CCXP-CORP-QUI006','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(428,'CCXP-CORP-QUI007','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(429,'CCXP-CORP-QUI008','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(430,'CCXP-CORP-QUI009','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(431,'CCXP-CORP-QUI010','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(432,'CCXP-CORP-QUI011','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(433,'CCXP-CORP-QUI012','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(434,'CCXP-CORP-SEX001','sexta','corporativo',NULL,'entregue',39,NULL,NULL);
INSERT INTO Codigo VALUES(435,'CCXP-CORP-SEX002','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(436,'CCXP-CORP-SEX003','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(437,'CCXP-CORP-SEX004','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(438,'CCXP-CORP-SEX005','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(439,'CCXP-CORP-SEX006','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(440,'CCXP-CORP-SEX007','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(441,'CCXP-CORP-SEX008','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(442,'CCXP-CORP-SEX009','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(443,'CCXP-CORP-SEX010','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(444,'CCXP-CORP-SEX011','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(445,'CCXP-CORP-SEX012','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(446,'CCXP-CORP-SAB001','sabado','corporativo',NULL,'entregue',33,NULL,NULL);
INSERT INTO Codigo VALUES(447,'CCXP-CORP-SAB002','sabado','corporativo',NULL,'entregue',33,NULL,NULL);
INSERT INTO Codigo VALUES(448,'CCXP-CORP-SAB003','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(449,'CCXP-CORP-SAB004','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(450,'CCXP-CORP-SAB005','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(451,'CCXP-CORP-SAB006','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(452,'CCXP-CORP-SAB007','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(453,'CCXP-CORP-SAB008','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(454,'CCXP-CORP-SAB009','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(455,'CCXP-CORP-SAB010','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(456,'CCXP-CORP-SAB011','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(457,'CCXP-CORP-SAB012','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(458,'CCXP-CORP-DOM001','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(459,'CCXP-CORP-DOM002','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(460,'CCXP-CORP-DOM003','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(461,'CCXP-CORP-DOM004','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(462,'CCXP-CORP-DOM005','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(463,'CCXP-CORP-DOM006','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(464,'CCXP-CORP-DOM007','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(465,'CCXP-CORP-DOM008','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(466,'CCXP-CORP-DOM009','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(467,'CCXP-CORP-DOM010','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(468,'CCXP-CORP-DOM011','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(469,'CCXP-CORP-DOM012','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(470,'CCXP-CORP-TOD001','todos_os_dias','corporativo',NULL,'reservado',31,NULL,NULL);
INSERT INTO Codigo VALUES(471,'CCXP-CORP-TOD002','todos_os_dias','corporativo',NULL,'reservado',31,NULL,NULL);
INSERT INTO Codigo VALUES(472,'CCXP-CORP-TOD003','todos_os_dias','corporativo',NULL,'resgatado',37,'2026-06-09T21:59:01.625+00:00',NULL);
INSERT INTO Codigo VALUES(473,'CCXP-CORP-TOD004','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(474,'CCXP-CORP-TOD005','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(475,'CCXP-CORP-TOD006','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(476,'CCXP-CORP-TOD007','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(477,'CCXP-CORP-TOD008','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(478,'CCXP-CORP-TOD009','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(479,'CCXP-CORP-TOD010','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(480,'CCXP-CORP-TOD011','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(481,'CCXP-CORP-TOD012','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO ComunicacaoLog VALUES(25,28,'transacional','convite','email','enviado','2026-06-10T21:59:01.631+00:00');
INSERT INTO ComunicacaoLog VALUES(26,30,'transacional','convite','email','enviado','2026-06-07T21:59:01.632+00:00');
INSERT INTO ComunicacaoLog VALUES(27,30,'transacional','instrucao_resgate','email','enviado','2026-06-08T21:59:01.633+00:00');
INSERT INTO ComunicacaoLog VALUES(28,31,'transacional','convite','email','enviado','2026-06-02T21:59:01.633+00:00');
INSERT INTO ComunicacaoLog VALUES(29,31,'transacional','lembrete_cadastro','email','enviado','2026-06-05T21:59:01.634+00:00');
INSERT INTO ComunicacaoLog VALUES(30,31,'transacional','aviso_expiracao','email','enviado','2026-06-08T21:59:01.634+00:00');
INSERT INTO ComunicacaoLog VALUES(31,33,'regua','d-7_falta_uma_semana','email','enviado','2026-06-10T21:59:01.634+00:00');
INSERT INTO ComunicacaoLog VALUES(32,35,'transacional','convite','email','enviado','2026-06-08T21:59:01.635+00:00');
INSERT INTO ReguaPasso VALUES(1,'transacional',1,'Convite','imediato',NULL,'email,whatsapp',NULL,'Você foi convidado pra CCXP26','Olá, {{nome}}! {{host}} convidou você pra CCXP26 (03 a 06/dez, São Paulo Expo) com {{qtd}} ingresso(s): {{tipos}}. Complete seu cadastro pra receber os códigos: {{link}}',1);
INSERT INTO ReguaPasso VALUES(2,'transacional',2,'Lembrete de cadastro','D+3',NULL,'email,whatsapp','pular_se_cadastrado','Seus ingressos da CCXP26 esperam por você','{{nome}}, seus {{qtd}} ingresso(s) seguem reservados, mas o cadastro ainda não foi concluído. Leva 1 minuto: {{link}}',1);
INSERT INTO ReguaPasso VALUES(3,'transacional',3,'Aviso de expiração','D+6',NULL,'email,whatsapp','pular_se_cadastrado','Último dia: seu convite expira amanhã','{{nome}}, seu convite pra CCXP26 expira amanhã e os ingressos voltam ao pool. Garanta os seus: {{link}}',1);
INSERT INTO ReguaPasso VALUES(4,'transacional',4,'Instrução de resgate','após cadastro',NULL,'email',NULL,'Como resgatar seus ingressos na Mundo Ticket','{{nome}}, seus códigos estão na sua carteira. Resgate na Mundo Ticket com o passo a passo: {{link}}. Qualquer dúvida, fale com {{host}}.',1);
INSERT INTO ReguaPasso VALUES(5,'regua',1,'Falta uma semana','D-7','2026-11-26','email',NULL,'Falta uma semana pra CCXP26','{{nome}}, em 7 dias a CCXP26 abre os portões no São Paulo Expo. Como chegar, por onde entrar e o que levar: tudo neste guia. Seus ingressos: {{tipos}}.',1);
INSERT INTO ReguaPasso VALUES(6,'regua',2,'Lembrete de resgate','D-3','2026-11-30','email,whatsapp','pular_se_resgatado','Já resgatou seus ingressos?','{{nome}}, faltam 3 dias e seus códigos ainda não foram resgatados na Mundo Ticket. Resolve agora em 2 minutos: {{link}}. Mapa do evento em anexo.',1);
INSERT INTO ReguaPasso VALUES(7,'regua',3,'Véspera: agenda do dia','D-1','2026-12-02','email',NULL,'Amanhã tem CCXP26: sua agenda','{{nome}}, amanhã começa! Agenda do dia, dicas práticas e o lounge VIP Omelete te esperando. Credenciamento VIP abre 1h antes dos portões.',1);
INSERT INTO ReguaPasso VALUES(8,'regua',4,'É hoje','Dia 1','2026-12-03','whatsapp',NULL,'É hoje! CCXP26 abre às 12h','{{nome}}, chegou o dia. Destaques de hoje no Palco Thunder, entrada VIP pela entrada Sul. Bom evento!',1);
INSERT INTO ReguaPasso VALUES(9,'transacional',1,'Convite','imediato',NULL,'email,whatsapp',NULL,'Você foi convidado pra CCXP26','Olá, {{nome}}! {{host}} convidou você pra CCXP26 (03 a 06/dez, São Paulo Expo) com {{qtd}} ingresso(s): {{tipos}}. Complete seu cadastro pra receber os códigos: {{link}}',1);
INSERT INTO ReguaPasso VALUES(10,'transacional',2,'Lembrete de cadastro','D+3',NULL,'email,whatsapp','pular_se_cadastrado','Seus ingressos da CCXP26 esperam por você','{{nome}}, seus {{qtd}} ingresso(s) seguem reservados, mas o cadastro ainda não foi concluído. Leva 1 minuto: {{link}}',1);
INSERT INTO ReguaPasso VALUES(11,'transacional',3,'Aviso de expiração','D+6',NULL,'email,whatsapp','pular_se_cadastrado','Último dia: seu convite expira amanhã','{{nome}}, seu convite pra CCXP26 expira amanhã e os ingressos voltam ao pool. Garanta os seus: {{link}}',1);
INSERT INTO ReguaPasso VALUES(12,'transacional',4,'Instrução de resgate','após cadastro',NULL,'email',NULL,'Como resgatar seus ingressos na Mundo Ticket','{{nome}}, seus códigos estão na sua carteira. Resgate na Mundo Ticket com o passo a passo: {{link}}. Qualquer dúvida, fale com {{host}}.',1);
INSERT INTO ReguaPasso VALUES(13,'regua',1,'Falta uma semana','D-7','2026-11-26','email',NULL,'Falta uma semana pra CCXP26','{{nome}}, em 7 dias a CCXP26 abre os portões no São Paulo Expo. Como chegar, por onde entrar e o que levar: tudo neste guia. Seus ingressos: {{tipos}}.',1);
INSERT INTO ReguaPasso VALUES(14,'regua',2,'Lembrete de resgate','D-3','2026-11-30','email,whatsapp','pular_se_resgatado','Já resgatou seus ingressos?','{{nome}}, faltam 3 dias e seus códigos ainda não foram resgatados na Mundo Ticket. Resolve agora em 2 minutos: {{link}}. Mapa do evento em anexo.',1);
INSERT INTO ReguaPasso VALUES(15,'regua',3,'Véspera: agenda do dia','D-1','2026-12-02','email',NULL,'Amanhã tem CCXP26: sua agenda','{{nome}}, amanhã começa! Agenda do dia, dicas práticas e o lounge VIP Omelete te esperando. Credenciamento VIP abre 1h antes dos portões.',1);
INSERT INTO ReguaPasso VALUES(16,'regua',4,'É hoje','Dia 1','2026-12-03','whatsapp',NULL,'É hoje! CCXP26 abre às 12h','{{nome}}, chegou o dia. Destaques de hoje no Palco Thunder, entrada VIP pela entrada Sul. Bom evento!',1);
INSERT INTO ReguaPasso VALUES(17,'pos_evento',1,'Agradecimento + fotos','D+1','2026-12-07','email',NULL,'Obrigado por viver a CCXP26 com a gente','{{nome}}, foi incrível ter você na CCXP26. As fotos do lounge VIP Omelete já estão disponíveis na sua conta: {{link}}',1);
INSERT INTO ReguaPasso VALUES(18,'pos_evento',2,'Pesquisa de satisfação','D+3','2026-12-09','email',NULL,'2 minutos: como foi sua CCXP26?','{{nome}}, sua opinião define a próxima edição. Responda a pesquisa rápida (NPS + 3 perguntas): {{link}}',1);
INSERT INTO ReguaPasso VALUES(19,'pos_evento',3,'Números + after movie','D+7','2026-12-13','email',NULL,'CCXP26 em números (e o after movie)','{{nome}}, a CCXP26 em números: público, palcos e os melhores momentos no after movie. Assista e compartilhe: {{link}}',1);
INSERT INTO ReguaPasso VALUES(20,'transacional',1,'Convite','imediato',NULL,'email,whatsapp',NULL,'Você foi convidado pra CCXP26','Olá, {{nome}}! {{host}} convidou você pra CCXP26 (03 a 06/dez, São Paulo Expo) com {{qtd}} ingresso(s): {{tipos}}. Complete seu cadastro pra receber os códigos: {{link}}',1);
INSERT INTO ReguaPasso VALUES(21,'transacional',2,'Lembrete de cadastro','D+3',NULL,'email,whatsapp','pular_se_cadastrado','Seus ingressos da CCXP26 esperam por você','{{nome}}, seus {{qtd}} ingresso(s) seguem reservados, mas o cadastro ainda não foi concluído. Leva 1 minuto: {{link}}',1);
INSERT INTO ReguaPasso VALUES(22,'transacional',3,'Aviso de expiração','D+6',NULL,'email,whatsapp','pular_se_cadastrado','Último dia: seu convite expira amanhã','{{nome}}, seu convite pra CCXP26 expira amanhã e os ingressos voltam ao pool. Garanta os seus: {{link}}',1);
INSERT INTO ReguaPasso VALUES(23,'transacional',4,'Instrução de resgate','após cadastro',NULL,'email',NULL,'Como resgatar seus ingressos na Mundo Ticket','{{nome}}, seus códigos estão na sua carteira. Resgate na Mundo Ticket com o passo a passo: {{link}}. Qualquer dúvida, fale com {{host}}.',1);
INSERT INTO ReguaPasso VALUES(24,'regua',1,'Falta uma semana','D-7','2026-11-26','email',NULL,'Falta uma semana pra CCXP26','{{nome}}, em 7 dias a CCXP26 abre os portões no São Paulo Expo. Como chegar, por onde entrar e o que levar: tudo neste guia. Seus ingressos: {{tipos}}.',1);
INSERT INTO ReguaPasso VALUES(25,'regua',2,'Lembrete de resgate','D-3','2026-11-30','email,whatsapp','pular_se_resgatado','Já resgatou seus ingressos?','{{nome}}, faltam 3 dias e seus códigos ainda não foram resgatados na Mundo Ticket. Resolve agora em 2 minutos: {{link}}. Mapa do evento em anexo.',1);
INSERT INTO ReguaPasso VALUES(26,'regua',3,'Véspera: agenda do dia','D-1','2026-12-02','email',NULL,'Amanhã tem CCXP26: sua agenda','{{nome}}, amanhã começa! Agenda do dia, dicas práticas e o lounge VIP Omelete te esperando. Credenciamento VIP abre 1h antes dos portões.',1);
INSERT INTO ReguaPasso VALUES(27,'regua',4,'É hoje','Dia 1','2026-12-03','whatsapp',NULL,'É hoje! CCXP26 abre às 12h','{{nome}}, chegou o dia. Destaques de hoje no Palco Thunder, entrada VIP pela entrada Sul. Bom evento!',1);
INSERT INTO ReguaPasso VALUES(28,'pos_evento',1,'Agradecimento + fotos','D+1','2026-12-07','email',NULL,'Obrigado por viver a CCXP26 com a gente','{{nome}}, foi incrível ter você na CCXP26. As fotos do lounge VIP Omelete já estão disponíveis na sua conta: {{link}}',1);
INSERT INTO ReguaPasso VALUES(29,'pos_evento',2,'Pesquisa de satisfação','D+3','2026-12-09','email',NULL,'2 minutos: como foi sua CCXP26?','{{nome}}, sua opinião define a próxima edição. Responda a pesquisa rápida (NPS + 3 perguntas): {{link}}',1);
INSERT INTO ReguaPasso VALUES(30,'pos_evento',3,'Números + after movie','D+7','2026-12-13','email',NULL,'CCXP26 em números (e o after movie)','{{nome}}, a CCXP26 em números: público, palcos e os melhores momentos no after movie. Assista e compartilhe: {{link}}',1);
INSERT INTO AgendaItem VALUES(13,'2026-12-03','11:00','Abertura dos portões','Credenciamento VIP na entrada Sul do São Paulo Expo.');
INSERT INTO AgendaItem VALUES(14,'2026-12-03','14:00','Painel de abertura · Palco Thunder','Apresentação oficial da CCXP26.');
INSERT INTO AgendaItem VALUES(15,'2026-12-05','16:00','Painel principal · Palco Thunder','Convidado internacional surpresa.');
INSERT INTO AgendaItem VALUES(16,'2026-12-06','18:00','Encerramento','Último dia: recap e agradecimentos.');
INSERT INTO DominioBloqueado VALUES(40,'gmail.com');
INSERT INTO DominioBloqueado VALUES(41,'hotmail.com');
INSERT INTO DominioBloqueado VALUES(42,'outlook.com');
INSERT INTO DominioBloqueado VALUES(43,'yahoo.com');
INSERT INTO DominioBloqueado VALUES(44,'icloud.com');
INSERT INTO DominioBloqueado VALUES(45,'live.com');
INSERT INTO DominioBloqueado VALUES(46,'msn.com');
INSERT INTO DominioBloqueado VALUES(47,'aol.com');
INSERT INTO DominioBloqueado VALUES(48,'proton.me');
INSERT INTO DominioBloqueado VALUES(49,'protonmail.com');
INSERT INTO DominioBloqueado VALUES(50,'gmx.com');
INSERT INTO DominioBloqueado VALUES(51,'mail.com');
INSERT INTO DominioBloqueado VALUES(52,'yandex.com');
INSERT INTO AuditLog VALUES(13,10,'import_planilha_mestre','planilha','55 códigos pessoais importados (Modo A)','2026-05-30T21:59:01.643+00:00');
INSERT INTO AuditLog VALUES(14,10,'import_lote_corporativo','planilha','72 códigos corporativos importados','2026-05-30T21:59:01.643+00:00');
INSERT INTO AuditLog VALUES(15,12,'cancelar_convite','convite:Davi Fontes','1 código devolvido ao pool pessoal','2026-06-07T21:59:01.643+00:00');
INSERT INTO AuditLog VALUES(16,10,'editar_flag_vip','convidado:Elisa Prado','vip_omelete: false → true','2026-06-06T21:59:01.643+00:00');
INSERT INTO Config VALUES('expiracao_dias','7');
INSERT INTO Config VALUES('evento_inicio','2026-12-03');
INSERT INTO Config VALUES('evento_fim','2026-12-06');
INSERT INTO Config VALUES('evento_local','São Paulo Expo');
INSERT INTO Config VALUES('link_mundo_ticket','https://mundoticket.com.br/ccxp26/resgate');
