INSERT INTO Funcionario VALUES(13,'Beto Fabri','beto.fabri@omelete.com','vp_socio',1,1);
INSERT INTO Funcionario VALUES(14,'Camila Ramos','camila.ramos@omelete.com','diretoria',1,0);
INSERT INTO Funcionario VALUES(15,'Diego Lima','diego.lima@omelete.com','geral',0,0);
INSERT INTO Convidado VALUES(37,'Ana Beltrão','ana.beltrao@warnerbros.com',NULL,'Warner Bros.',NULL,NULL,NULL,0,0,NULL,NULL);
INSERT INTO Convidado VALUES(38,'Henrique Sato',NULL,'+5511955554444',NULL,NULL,NULL,NULL,0,0,NULL,NULL);
INSERT INTO Convidado VALUES(39,'Bruno Okamoto','bruno.okamoto@netflix.com',NULL,'Netflix','Diretor de Conteúdo','1988-03-14T00:00:00.000+00:00','2026-06-08T23:42:47.696+00:00',0,0,'@brunookamoto','linkedin.com/in/brunookamoto');
INSERT INTO Convidado VALUES(40,'Carla Mendes','carla.mendes@globo.com',NULL,'Globo',NULL,NULL,NULL,0,0,NULL,NULL);
INSERT INTO Convidado VALUES(41,'Davi Fontes',NULL,'+5511987654321',NULL,NULL,NULL,NULL,0,0,NULL,NULL);
INSERT INTO Convidado VALUES(42,'Elisa Prado','elisa.prado@paramount.com',NULL,'Paramount','Head de Distribuição','1985-11-02T00:00:00.000+00:00','2026-06-05T23:42:47.704+00:00',0,1,'@elisaprado','linkedin.com/in/elisaprado');
INSERT INTO Convidado VALUES(43,'Fábio Quintela','fabio.q@ubisoft.com',NULL,'Ubisoft','Brand Manager','1990-07-21T00:00:00.000+00:00','2026-06-01T23:42:47.708+00:00',0,1,NULL,NULL);
INSERT INTO Convidado VALUES(44,'Luís Hernandez','luis.hernandez@hbo.com',NULL,'HBO','VP de Programação','1979-05-30T00:00:00.000+00:00','2026-06-09T23:42:47.711+00:00',0,0,'@luishdz','linkedin.com/in/luishernandez');
INSERT INTO Convidado VALUES(45,'Gabi Torres',NULL,'+5511912345678',NULL,NULL,'1995-09-12T00:00:00.000+00:00','2026-06-10T23:42:47.717+00:00',0,0,NULL,NULL);
INSERT INTO Convite VALUES(41,13,37,'email','pendente','2026-06-17T23:42:47.675+00:00',1,'2026-06-10T23:42:47.676+00:00','tok-ana');
INSERT INTO Convite VALUES(42,15,38,'whatsapp','pendente','2026-06-16T23:42:47.693+00:00',0,'2026-06-09T23:42:47.693+00:00','tok-henrique');
INSERT INTO Convite VALUES(43,14,39,'email,whatsapp','cadastrado','2026-06-14T23:42:47.697+00:00',0,'2026-06-07T23:42:47.697+00:00','tok-bruno');
INSERT INTO Convite VALUES(44,14,40,'email','expirado','2026-06-09T23:42:47.701+00:00',0,'2026-06-02T23:42:47.701+00:00','tok-carla');
INSERT INTO Convite VALUES(45,15,41,'whatsapp','cancelado','2026-06-13T23:42:47.703+00:00',0,'2026-06-06T23:42:47.703+00:00','tok-davi');
INSERT INTO Convite VALUES(46,13,42,'email','cadastrado','2026-06-12T23:42:47.705+00:00',1,'2026-06-05T23:42:47.705+00:00','tok-elisa');
INSERT INTO Convite VALUES(47,14,43,'email','cadastrado','2026-06-08T23:42:47.708+00:00',0,'2026-06-01T23:42:47.708+00:00','tok-fabio');
INSERT INTO Convite VALUES(48,13,44,'email','cadastrado','2026-06-15T23:42:47.712+00:00',0,'2026-06-08T23:42:47.712+00:00','tok-luis-beto');
INSERT INTO Convite VALUES(49,14,44,'email','cadastrado','2026-06-15T23:42:47.715+00:00',1,'2026-06-09T23:42:47.715+00:00','tok-luis-camila');
INSERT INTO Convite VALUES(50,15,45,'whatsapp','cadastrado','2026-06-16T23:42:47.718+00:00',0,'2026-06-09T23:42:47.718+00:00','tok-gabi');
INSERT INTO ConviteParcela VALUES(41,41,'corporativo','todos_os_dias',2,1);
INSERT INTO ConviteParcela VALUES(42,42,'pessoal','domingo',1,0);
INSERT INTO ConviteParcela VALUES(43,43,'corporativo','sabado',2,0);
INSERT INTO ConviteParcela VALUES(44,44,'corporativo','domingo',1,0);
INSERT INTO ConviteParcela VALUES(45,45,'pessoal','sexta',1,0);
INSERT INTO ConviteParcela VALUES(46,46,'corporativo','quinta',1,1);
INSERT INTO ConviteParcela VALUES(47,47,'corporativo','todos_os_dias',1,0);
INSERT INTO ConviteParcela VALUES(48,48,'pessoal','sabado',2,0);
INSERT INTO ConviteParcela VALUES(49,49,'corporativo','sexta',1,0);
INSERT INTO ConviteParcela VALUES(50,50,'pessoal','domingo',1,0);
INSERT INTO Codigo VALUES(482,'OMLT-BF-SAB1','sabado','pessoal',13,'entregue',48,NULL,NULL);
INSERT INTO Codigo VALUES(483,'OMLT-BF-SAB2','sabado','pessoal',13,'entregue',48,NULL,NULL);
INSERT INTO Codigo VALUES(484,'OMLT-CR-SPO1','spoiler_night','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(485,'OMLT-CR-SPO2','spoiler_night','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(486,'OMLT-CR-SPO3','spoiler_night','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(487,'OMLT-CR-SPO4','spoiler_night','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(488,'OMLT-CR-QUI1','quinta','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(489,'OMLT-CR-QUI2','quinta','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(490,'OMLT-CR-SEX1','sexta','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(491,'OMLT-CR-SEX2','sexta','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(492,'OMLT-CR-SEX3','sexta','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(493,'OMLT-CR-SAB1','sabado','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(494,'OMLT-CR-SAB2','sabado','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(495,'OMLT-CR-SAB3','sabado','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(496,'OMLT-CR-DOM1','domingo','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(497,'OMLT-CR-DOM2','domingo','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(498,'OMLT-CR-DOM3','domingo','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(499,'OMLT-CR-TOD1','todos_os_dias','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(500,'OMLT-CR-TOD2','todos_os_dias','pessoal',14,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(501,'OMLT-DL-SPO1','spoiler_night','pessoal',15,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(502,'OMLT-DL-SPO2','spoiler_night','pessoal',15,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(503,'OMLT-DL-SEX1','sexta','pessoal',15,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(504,'OMLT-DL-SEX2','sexta','pessoal',15,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(505,'OMLT-DL-SAB1','sabado','pessoal',15,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(506,'OMLT-DL-SAB2','sabado','pessoal',15,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(507,'OMLT-DL-DOM1','domingo','pessoal',15,'reservado',42,NULL,NULL);
INSERT INTO Codigo VALUES(508,'OMLT-DL-DOM2','domingo','pessoal',15,'entregue',50,NULL,NULL);
INSERT INTO Codigo VALUES(509,'OMLT-DL-TOD1','todos_os_dias','pessoal',15,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(510,'CCXP-CORP-SPO001','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(511,'CCXP-CORP-SPO002','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(512,'CCXP-CORP-SPO003','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(513,'CCXP-CORP-SPO004','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(514,'CCXP-CORP-SPO005','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(515,'CCXP-CORP-SPO006','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(516,'CCXP-CORP-SPO007','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(517,'CCXP-CORP-SPO008','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(518,'CCXP-CORP-SPO009','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(519,'CCXP-CORP-SPO010','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(520,'CCXP-CORP-SPO011','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(521,'CCXP-CORP-SPO012','spoiler_night','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(522,'CCXP-CORP-QUI001','quinta','corporativo',NULL,'entregue',46,NULL,NULL);
INSERT INTO Codigo VALUES(523,'CCXP-CORP-QUI002','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(524,'CCXP-CORP-QUI003','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(525,'CCXP-CORP-QUI004','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(526,'CCXP-CORP-QUI005','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(527,'CCXP-CORP-QUI006','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(528,'CCXP-CORP-QUI007','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(529,'CCXP-CORP-QUI008','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(530,'CCXP-CORP-QUI009','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(531,'CCXP-CORP-QUI010','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(532,'CCXP-CORP-QUI011','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(533,'CCXP-CORP-QUI012','quinta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(534,'CCXP-CORP-SEX001','sexta','corporativo',NULL,'entregue',49,NULL,NULL);
INSERT INTO Codigo VALUES(535,'CCXP-CORP-SEX002','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(536,'CCXP-CORP-SEX003','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(537,'CCXP-CORP-SEX004','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(538,'CCXP-CORP-SEX005','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(539,'CCXP-CORP-SEX006','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(540,'CCXP-CORP-SEX007','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(541,'CCXP-CORP-SEX008','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(542,'CCXP-CORP-SEX009','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(543,'CCXP-CORP-SEX010','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(544,'CCXP-CORP-SEX011','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(545,'CCXP-CORP-SEX012','sexta','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(546,'CCXP-CORP-SAB001','sabado','corporativo',NULL,'entregue',43,NULL,NULL);
INSERT INTO Codigo VALUES(547,'CCXP-CORP-SAB002','sabado','corporativo',NULL,'entregue',43,NULL,NULL);
INSERT INTO Codigo VALUES(548,'CCXP-CORP-SAB003','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(549,'CCXP-CORP-SAB004','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(550,'CCXP-CORP-SAB005','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(551,'CCXP-CORP-SAB006','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(552,'CCXP-CORP-SAB007','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(553,'CCXP-CORP-SAB008','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(554,'CCXP-CORP-SAB009','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(555,'CCXP-CORP-SAB010','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(556,'CCXP-CORP-SAB011','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(557,'CCXP-CORP-SAB012','sabado','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(558,'CCXP-CORP-DOM001','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(559,'CCXP-CORP-DOM002','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(560,'CCXP-CORP-DOM003','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(561,'CCXP-CORP-DOM004','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(562,'CCXP-CORP-DOM005','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(563,'CCXP-CORP-DOM006','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(564,'CCXP-CORP-DOM007','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(565,'CCXP-CORP-DOM008','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(566,'CCXP-CORP-DOM009','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(567,'CCXP-CORP-DOM010','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(568,'CCXP-CORP-DOM011','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(569,'CCXP-CORP-DOM012','domingo','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(570,'CCXP-CORP-TOD001','todos_os_dias','corporativo',NULL,'reservado',41,NULL,NULL);
INSERT INTO Codigo VALUES(571,'CCXP-CORP-TOD002','todos_os_dias','corporativo',NULL,'reservado',41,NULL,NULL);
INSERT INTO Codigo VALUES(572,'CCXP-CORP-TOD003','todos_os_dias','corporativo',NULL,'resgatado',47,'2026-06-09T23:42:47.710+00:00',NULL);
INSERT INTO Codigo VALUES(573,'CCXP-CORP-TOD004','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(574,'CCXP-CORP-TOD005','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(575,'CCXP-CORP-TOD006','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(576,'CCXP-CORP-TOD007','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(577,'CCXP-CORP-TOD008','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(578,'CCXP-CORP-TOD009','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(579,'CCXP-CORP-TOD010','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(580,'CCXP-CORP-TOD011','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO Codigo VALUES(581,'CCXP-CORP-TOD012','todos_os_dias','corporativo',NULL,'disponivel',NULL,NULL,NULL);
INSERT INTO ComunicacaoLog VALUES(33,37,'transacional','convite','email','enviado','2026-06-10T23:42:47.720+00:00');
INSERT INTO ComunicacaoLog VALUES(34,39,'transacional','convite','email','enviado','2026-06-07T23:42:47.721+00:00');
INSERT INTO ComunicacaoLog VALUES(35,39,'transacional','instrucao_resgate','email','enviado','2026-06-08T23:42:47.721+00:00');
INSERT INTO ComunicacaoLog VALUES(36,40,'transacional','convite','email','enviado','2026-06-02T23:42:47.721+00:00');
INSERT INTO ComunicacaoLog VALUES(37,40,'transacional','lembrete_cadastro','email','enviado','2026-06-05T23:42:47.722+00:00');
INSERT INTO ComunicacaoLog VALUES(38,40,'transacional','aviso_expiracao','email','enviado','2026-06-08T23:42:47.723+00:00');
INSERT INTO ComunicacaoLog VALUES(39,42,'regua','d-7_falta_uma_semana','email','enviado','2026-06-10T23:42:47.723+00:00');
INSERT INTO ComunicacaoLog VALUES(40,44,'transacional','convite','email','enviado','2026-06-08T23:42:47.724+00:00');
INSERT INTO ReguaPasso VALUES(1,'transacional',1,'Convite','imediato',NULL,'email,whatsapp',NULL,'Você foi convidado pra CCXP26','Olá, {{nome}}! {{host}} convidou você pra CCXP26 (03 a 06/dez, São Paulo Expo) com {{qtd}} ingresso(s): {{tipos}}. Complete seu cadastro pra receber os códigos: {{link}}',1);
INSERT INTO ReguaPasso VALUES(2,'transacional',2,'Lembrete de cadastro','D+3',NULL,'email,whatsapp','pular_se_cadastrado','Seus ingressos da CCXP26 esperam por você','{{nome}}, seus {{qtd}} ingresso(s) seguem reservados, mas o cadastro ainda não foi concluído. Leva 1 minuto: {{link}}',1);
INSERT INTO ReguaPasso VALUES(3,'transacional',3,'Aviso de expiração','D+6',NULL,'email,whatsapp','pular_se_cadastrado','Último dia: seu convite expira amanhã','{{nome}}, seu convite pra CCXP26 expira amanhã e os ingressos voltam ao pool. Garanta os seus: {{link}}',1);
INSERT INTO ReguaPasso VALUES(4,'transacional',4,'Instrução de resgate','após cadastro',NULL,'email',NULL,'Como resgatar seus ingressos na Mundo Ticket','{{nome}}, seus códigos estão na sua carteira. Resgate na Mundo Ticket com o passo a passo: {{link}}. Qualquer dúvida, fale com {{host}}.',1);
INSERT INTO ReguaPasso VALUES(5,'regua',1,'Falta uma semana','D-7','2026-11-26','email',NULL,'Falta uma semana pra CCXP26','{{nome}}, em 7 dias a CCXP26 abre os portões no São Paulo Expo. Como chegar, por onde entrar e o que levar: tudo neste guia. Seus ingressos: {{tipos}}.',1);
INSERT INTO ReguaPasso VALUES(6,'regua',2,'Lembrete de resgate','D-3','2026-11-30','email,whatsapp','pular_se_resgatado','Já resgatou seus ingressos?','{{nome}}, faltam 3 dias e seus códigos ainda não foram resgatados na Mundo Ticket. Resolve agora em 2 minutos: {{link}}. Mapa do evento em anexo.',1);
INSERT INTO ReguaPasso VALUES(7,'regua',3,'Véspera: agenda do dia','D-1','2026-12-02','email',NULL,'Amanhã tem CCXP26: sua agenda','{{nome}}, amanhã começa! Agenda do dia, dicas práticas e o lounge VIP Omelete te esperando. Credenciamento VIP abre 1h antes dos portões.',1);
INSERT INTO ReguaPasso VALUES(8,'regua',4,'É hoje','Dia 1','2026-12-03','whatsapp',NULL,'É hoje! CCXP26 abre às 12h','{{nome}}, chegou o dia. Destaques de hoje no Palco Thunder, entrada VIP pela entrada Sul. Bom evento!',1);
INSERT INTO ReguaPasso VALUES(9,'transacional',1,'Convite','imediato',NULL,'email,whatsapp',NULL,'Você foi convidado pra CCXP26','Olá, {{nome}}! {{host}} convidou você pra CCXP26 (03 a 06/dez, São Paulo Expo) com {{qtd}} ingresso(s): {{tipos}}. Complete seu cadastro pra receber os códigos: {{link}}',1);
INSERT INTO ReguaPasso VALUES(10,'transacional',2,'Lembrete de cadastro','D+3',NULL,'email,whatsapp','pular_se_cadastrado','Seus ingressos da CCXP26 esperam por você','{{nome}}, seus {{qtd}} ingresso(s) seguem reservados, mas o cadastro ainda não foi concluído. Leva 1 minuto: {{link}}',1);
INSERT INTO ReguaPasso VALUES(11,'transacional',3,'Aviso de expiração','D+6',NULL,'email,whatsapp','pular_se_cadastrado','Último dia: seu convite expira amanhã','{{nome}}, seu convite pra CCXP26 expira amanhã e os ingressos voltam ao pool. Garanta os seus: {{link}}',1);
INSERT INTO ReguaPasso VALUES(12,'transacional',4,'Instrução de resgate','após cadastro',NULL,'email',NULL,'Como resgatar seus ingressos na Mundo Ticket','{{nome}}, seus códigos estão na sua carteira. Resgate na Mundo Ticket com o passo a passo: {{link}}. Qualquer dúvida, fale com {{host}}.',1);
INSERT INTO ReguaPasso VALUES(13,'regua',1,'Falta uma semana','D-7','2026-11-26','email',NULL,'Falta uma semana pra CCXP26','{{nome}}, em 7 dias a CCXP26 abre os portões no São Paulo Expo. Como chegar, por onde entrar e o que levar: tudo neste guia. Seus ingressos: {{tipos}}.',1);
INSERT INTO ReguaPasso VALUES(14,'regua',2,'Lembrete de resgate','D-3','2026-11-30','email,whatsapp','pular_se_resgatado','Já resgatou seus ingressos?','{{nome}}, faltam 3 dias e seus códigos ainda não foram resgatados na Mundo Ticket. Resolve agora em 2 minutos: {{link}}. Mapa do evento em anexo.',1);
INSERT INTO ReguaPasso VALUES(15,'regua',3,'Véspera: agenda do dia','D-1','2026-12-02','email',NULL,'Amanhã tem CCXP26: sua agenda','{{nome}}, amanhã começa! Agenda do dia, dicas práticas e o lounge VIP Omelete te esperando. Credenciamento VIP abre 1h antes dos portões.',1);
INSERT INTO ReguaPasso VALUES(16,'regua',4,'É hoje','Dia 1','2026-12-03','whatsapp',NULL,'É hoje! CCXP26 abre às 12h','{{nome}}, chegou o dia. Destaques de hoje no Palco Thunder, entrada VIP pela entrada Sul. Bom evento!',1);
INSERT INTO ReguaPasso VALUES(17,'pos_evento',1,'Agradecimento + fotos','D+1','2026-12-07','email',NULL,'Obrigado por viver a CCXP26 com a gente','{{nome}}, foi incrível ter você na CCXP26. As fotos do lounge VIP Omelete já estão disponíveis na sua conta: {{link}}',1);
INSERT INTO ReguaPasso VALUES(18,'pos_evento',2,'Pesquisa de satisfação','D+3','2026-12-09','email',NULL,'2 minutos: como foi sua CCXP26?','{{nome}}, sua opinião define a próxima edição. Responda a pesquisa rápida (NPS + 3 perguntas): {{link}}',1);
INSERT INTO ReguaPasso VALUES(19,'pos_evento',3,'Números + after movie','D+7','2026-12-13','email',NULL,'CCXP26 em números (e o after movie)','{{nome}}, a CCXP26 em números: público, palcos e os melhores momentos no after movie. Assista e compartilhe: {{link}}',1);
INSERT INTO ReguaPasso VALUES(20,'transacional',1,'Convite','imediato',NULL,'email,whatsapp',NULL,'Você foi convidado pra CCXP26','Olá, {{nome}}! {{host}} convidou você pra CCXP26 (03 a 06/dez, São Paulo Expo) com {{qtd}} ingresso(s): {{tipos}}. Complete seu cadastro pra receber os códigos: {{link}}',1);
INSERT INTO ReguaPasso VALUES(21,'transacional',2,'Lembrete de cadastro','D+3',NULL,'email,whatsapp','pular_se_cadastrado','Seus ingressos da CCXP26 esperam por você','{{nome}}, seus {{qtd}} ingresso(s) seguem reservados, mas o cadastro ainda não foi concluído. Leva 1 minuto: {{link}}',1);
INSERT INTO ReguaPasso VALUES(22,'transacional',3,'Aviso de expiração','D+6',NULL,'email,whatsapp','pular_se_cadastrado','Último dia: seu convite expira amanhã','{{nome}}, seu convite pra CCXP26 expira amanhã e os ingressos voltam ao pool. Garanta os seus: {{link}}',1);
INSERT INTO ReguaPasso VALUES(23,'transacional',4,'Instrução de resgate','após cadastro',NULL,'email',NULL,'Como resgatar seus ingressos na Mundo Ticket','{{nome}}, seus códigos estão na sua carteira. Resgate na Mundo Ticket com o passo a passo: {{link}}. Qualquer dúvida, fale com {{host}}.',1);
INSERT INTO ReguaPasso VALUES(24,'regua',1,'Falta uma semana','D-7','2026-11-26','email',NULL,'Falta uma semana pra CCXP26','{{nome}}, em 7 dias a CCXP26 abre os portões no São Paulo Expo. Como chegar, por onde entrar e o que levar: tudo neste guia. Seus ingressos: {{tipos}}.',1);
INSERT INTO ReguaPasso VALUES(25,'regua',2,'Lembrete de resgate','D-3','2026-11-30','email,whatsapp','pular_se_resgatado','Já resgatou seus ingressos?','{{nome}}, faltam 3 dias e seus códigos ainda não foram resgatados na Mundo Ticket. Resolve agora em 2 minutos: {{link}}. Mapa do evento em anexo.',1);
INSERT INTO ReguaPasso VALUES(26,'regua',3,'Véspera: agenda do dia','D-1','2026-12-02','email',NULL,'Amanhã tem CCXP26: sua agenda','{{nome}}, amanhã começa! Agenda do dia, dicas práticas e o lounge VIP Omelete te esperando. Credenciamento VIP abre 1h antes dos portões.',1);
INSERT INTO ReguaPasso VALUES(27,'regua',4,'É hoje','Dia 1','2026-12-03','whatsapp',NULL,'É hoje! CCXP26 abre às 12h','{{nome}}, chegou o dia. Destaques de hoje no Palco Thunder, entrada VIP pela entrada Sul. Bom evento!',1);
INSERT INTO ReguaPasso VALUES(28,'pos_evento',1,'Agradecimento + fotos','D+1','2026-12-07','email',NULL,'Obrigado por viver a CCXP26 com a gente','{{nome}}, foi incrível ter você na CCXP26. As fotos do lounge VIP Omelete já estão disponíveis na sua conta: {{link}}',1);
INSERT INTO ReguaPasso VALUES(29,'pos_evento',2,'Pesquisa de satisfação','D+3','2026-12-09','email',NULL,'2 minutos: como foi sua CCXP26?','{{nome}}, sua opinião define a próxima edição. Responda a pesquisa rápida (NPS + 3 perguntas): {{link}}',1);
INSERT INTO ReguaPasso VALUES(30,'pos_evento',3,'Números + after movie','D+7','2026-12-13','email',NULL,'CCXP26 em números (e o after movie)','{{nome}}, a CCXP26 em números: público, palcos e os melhores momentos no after movie. Assista e compartilhe: {{link}}',1);
INSERT INTO ReguaPasso VALUES(31,'transacional',1,'Convite','imediato',NULL,'email,whatsapp',NULL,'Você foi convidado pra CCXP26','Olá, {{nome}}! {{host}} convidou você pra CCXP26 (03 a 06/dez, São Paulo Expo) com {{qtd}} ingresso(s): {{tipos}}. Complete seu cadastro pra receber os códigos: {{link}}',1);
INSERT INTO ReguaPasso VALUES(32,'transacional',2,'Lembrete de cadastro','D+3',NULL,'email,whatsapp','pular_se_cadastrado','Seus ingressos da CCXP26 esperam por você','{{nome}}, seus {{qtd}} ingresso(s) seguem reservados, mas o cadastro ainda não foi concluído. Leva 1 minuto: {{link}}',1);
INSERT INTO ReguaPasso VALUES(33,'transacional',3,'Aviso de expiração','D+6',NULL,'email,whatsapp','pular_se_cadastrado','Último dia: seu convite expira amanhã','{{nome}}, seu convite pra CCXP26 expira amanhã e os ingressos voltam ao pool. Garanta os seus: {{link}}',1);
INSERT INTO ReguaPasso VALUES(34,'transacional',4,'Instrução de resgate','após cadastro',NULL,'email',NULL,'Como resgatar seus ingressos na Mundo Ticket','{{nome}}, seus códigos estão na sua carteira. Resgate na Mundo Ticket com o passo a passo: {{link}}. Qualquer dúvida, fale com {{host}}.',1);
INSERT INTO ReguaPasso VALUES(35,'regua',1,'Falta uma semana','D-7','2026-11-26','email',NULL,'Falta uma semana pra CCXP26','{{nome}}, em 7 dias a CCXP26 abre os portões no São Paulo Expo. Como chegar, por onde entrar e o que levar: tudo neste guia. Seus ingressos: {{tipos}}.',1);
INSERT INTO ReguaPasso VALUES(36,'regua',2,'Lembrete de resgate','D-3','2026-11-30','email,whatsapp','pular_se_resgatado','Já resgatou seus ingressos?','{{nome}}, faltam 3 dias e seus códigos ainda não foram resgatados na Mundo Ticket. Resolve agora em 2 minutos: {{link}}. Mapa do evento em anexo.',1);
INSERT INTO ReguaPasso VALUES(37,'regua',3,'Véspera: agenda do dia','D-1','2026-12-02','email',NULL,'Amanhã tem CCXP26: sua agenda','{{nome}}, amanhã começa! Agenda do dia, dicas práticas e o lounge VIP Omelete te esperando. Credenciamento VIP abre 1h antes dos portões.',1);
INSERT INTO ReguaPasso VALUES(38,'regua',4,'É hoje','Dia 1','2026-12-03','whatsapp',NULL,'É hoje! CCXP26 abre às 12h','{{nome}}, chegou o dia. Destaques de hoje no Palco Thunder, entrada VIP pela entrada Sul. Bom evento!',1);
INSERT INTO ReguaPasso VALUES(39,'pos_evento',1,'Agradecimento + fotos','D+1','2026-12-07','email',NULL,'Obrigado por viver a CCXP26 com a gente','{{nome}}, foi incrível ter você na CCXP26. As fotos do lounge VIP Omelete já estão disponíveis na sua conta: {{link}}',1);
INSERT INTO ReguaPasso VALUES(40,'pos_evento',2,'Pesquisa de satisfação','D+3','2026-12-09','email',NULL,'2 minutos: como foi sua CCXP26?','{{nome}}, sua opinião define a próxima edição. Responda a pesquisa rápida (NPS + 3 perguntas): {{link}}',1);
INSERT INTO ReguaPasso VALUES(41,'pos_evento',3,'Números + after movie','D+7','2026-12-13','email',NULL,'CCXP26 em números (e o after movie)','{{nome}}, a CCXP26 em números: público, palcos e os melhores momentos no after movie. Assista e compartilhe: {{link}}',1);
INSERT INTO AgendaItem VALUES(17,'2026-12-03','11:00','Abertura dos portões','Credenciamento VIP na entrada Sul do São Paulo Expo.');
INSERT INTO AgendaItem VALUES(18,'2026-12-03','14:00','Painel de abertura · Palco Thunder','Apresentação oficial da CCXP26.');
INSERT INTO AgendaItem VALUES(19,'2026-12-05','16:00','Painel principal · Palco Thunder','Convidado internacional surpresa.');
INSERT INTO AgendaItem VALUES(20,'2026-12-06','18:00','Encerramento','Último dia: recap e agradecimentos.');
INSERT INTO DominioBloqueado VALUES(53,'gmail.com');
INSERT INTO DominioBloqueado VALUES(54,'hotmail.com');
INSERT INTO DominioBloqueado VALUES(55,'outlook.com');
INSERT INTO DominioBloqueado VALUES(56,'yahoo.com');
INSERT INTO DominioBloqueado VALUES(57,'icloud.com');
INSERT INTO DominioBloqueado VALUES(58,'live.com');
INSERT INTO DominioBloqueado VALUES(59,'msn.com');
INSERT INTO DominioBloqueado VALUES(60,'aol.com');
INSERT INTO DominioBloqueado VALUES(61,'proton.me');
INSERT INTO DominioBloqueado VALUES(62,'protonmail.com');
INSERT INTO DominioBloqueado VALUES(63,'gmx.com');
INSERT INTO DominioBloqueado VALUES(64,'mail.com');
INSERT INTO DominioBloqueado VALUES(65,'yandex.com');
INSERT INTO AuditLog VALUES(17,13,'import_planilha_mestre','planilha','55 códigos pessoais importados (Modo A)','2026-05-30T23:42:47.735+00:00');
INSERT INTO AuditLog VALUES(18,13,'import_lote_corporativo','planilha','72 códigos corporativos importados','2026-05-30T23:42:47.735+00:00');
INSERT INTO AuditLog VALUES(19,15,'cancelar_convite','convite:Davi Fontes','1 código devolvido ao pool pessoal','2026-06-07T23:42:47.735+00:00');
INSERT INTO AuditLog VALUES(20,13,'editar_flag_vip','convidado:Elisa Prado','vip_omelete: false → true','2026-06-06T23:42:47.735+00:00');
INSERT INTO Config VALUES('expiracao_dias','7');
INSERT INTO Config VALUES('evento_inicio','2026-12-03');
INSERT INTO Config VALUES('evento_fim','2026-12-06');
INSERT INTO Config VALUES('evento_local','São Paulo Expo');
INSERT INTO Config VALUES('link_mundo_ticket','https://mundoticket.com.br/ccxp26/resgate');
